### ISSUE TITLE
Design UX test around entry to site:  Do users understand Icons and what they do?

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB_UX#2]

**Comment by temjones** [comment]
My view is that this question: Do users understand Icons and what they do? Will be probed in different stages - initial first impressions, and later, indirectly when asking users to perform specific tasks. This ticket refers to entry to site - so I will focus on that, and add some explicit testing of some icons, but, of course, a lot of the real test of whether these icons are intuitive will be also happen during specific task- testing.

Upon entry to the site, we could ask questions like:

"Could you describe what you notice first when looking at this page? What kinds of things do you think can be done on this page? What do you think you would click on first?"

"Without clicking on anything for now, what would you guess each of these icons along the top does, or what they might be useful for? What about the icons on the left?" etc

[Explicit test for search icon]
"Do you have a favourite neuron/brain region? [if yes] How do you think you might find information about that structure on this website? [if no, suggest a pre-selected region and ask similar question]"

[once user has carried out a successful search for some neuroanatomy]
"What options does this website give you when you are searching for your region of interest? [aiming for the "Show info" and "Add to Query" options] What do you think these options mean? What do you expect to happen when you click on Show Info? [follow up with same question for Add to Query]"

[Have user click on "add to query"]
"What options do you have now that you have added this structure to a query? What would you be most likely to do on this page?"
[I would prefer to really let the user lead the way for a bit here, figuring out what they can do, looking at the options, talking through their thought process - if they have a preference as to what to search for, let them go ahead and do that. Pay attention to whether they understand the input format of the query, and whether it's intuitive for them to get to results, what can they do with results?]

[Once user has some painted regions showing - maybe after a particular task test]
[Explicit test for control panel icon]
"How would you find a list of all the structures that are shown in your current view?"

[Have user close the Term Info and Slice Viewer panels before playing with 3D navigation tools]
[Explicit test for left hand icons]
"Can you show me what you would do to change the angle of your view? Or how to change the zoom?"

[Explicit test for Term Info and Slice Viewer icons]
"Okay, now suppose you want to look through a Z stack of the same structures shown in this view. Can you show me how you might do that?"
"And what if we wanted to see the more detailed information about one of these structures again? Can you show me how you would find that?"
