### ISSUE TITLE
Write up plan for VFB UX based on Krug books

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB_UX#3]
- Don't make me think
- Rocket surgery made easy

**Comment by aoifelarkin** [comment]
Have had a look at the Steve Krug books, good background for something I didn't know much about. My general take home messages from the books and thoughts for our first test session would be:

1. might be best/easiest to have participants use one of our own laptops for the testing, as this would mean less messing around with trying to install things and decreases the possibility of things going wrong (I know Robbie mentioned it would be nice to check for bugs in different environments but maybe this can be done separately, or in the next session once we have a better feel for how to run these?); laptop would need to be able to screen share, screen record, may need a mic (or test laptop mic)

2. follow the [Steve Krug script](http://sensible.com/downloads/test-script-web.pdf) with some small tweaks to gauge also how Drosophila/neuro/vfb savvy they are

3. do the 3 volunteers one after the other in a morning, 1hr each if possible - would be good if people followed along live if they can (via screen sharing software)

4. have a scheduled chat of all interested parties after the sessions (maybe the next day given our distributed locations, would give people who didn't watch live a chance to watch the videos): everyone watching comes up with 3 most serious usability problems they think should be fixed, then we rank these problems and decide which ones to focus on before the next UX testing session

5. after the basic homepage feedback for a couple of minutes, here are some ideas for possible questions one might want to answer using the VFB website; I reckon we should decide which ones might be most useful to test, turn them into tasks, then try them out beforehand to get an idea of how long they are (so we can see how many might fit in during a test and have backups in case people are speedy)..Given the questions David thought it would be best to try and answer with this UX test ([VFB_UX 1](https://github.com/VirtualFlyBrain/VFB_UX/issues/1): is the nomenclature clear - templates, painted domains & [VFB_UX 2](https://github.com/VirtualFlyBrain/VFB_UX/issues/2): do users understand icons and what they do?), maybe a task that involves use of different templates and some obscure painted domains, and some task(s) that involve differential use of at least a couple of the icons.
a. What connections are there to or from my ROI?
b. What neurons have synaptic terminals in my ROI?
c. what GAL4s target my ROI?
d. What neurons develop from a particular neuroblast?
e. what is the function of this ROI?
f. I need an image of this GAL4 I've been using, to see what regions are being targeted.
g. I would like to see all regions of the brain involved in (e.g.) olfaction
h. What and where are (e.g.) the mushroom bodies?

Marta has sent me the email address of the volunteers, and we should probably arrange a date with them already if we want to get a UX test in before Christmas. Maybe the morning of Wed 13th Dec (too soon to get organized?)? Could schedule them for 9:30/10:30/11:30 maybe?

**Comment by ah963** [comment]
Having read the books (well skimmed the longer one)...

I'm happy to volunteer the use of my laptop for this. I have a plug in for chrome ([loom](https://www.useloom.com/)) that works well for capturing screens and audio and makes it relatively easy to share the captured files. 

In terms of tasks, replicating the existing examples given on the  VFB 1.5 homepage might be easiest with a couple of tweaks? I don't know if the original examples were user tested at the time so we could compare @dosumis? 

![screen shot 2017-11-28 at 09 39 45](https://user-images.githubusercontent.com/26765505/33312616-4d385d44-d420-11e7-8d61-5a7de190ff2d.png)

We also should test use of the 3D model - ask the users to zoom in on a specific brain region, rotate in XYZ, , identify a specific plane, use the slice viewer, etc. These could be added on to the original tasks - find an image of a neuron that has a part in the MB, select the parts of the MB and zoom in and rotate to capture an image for a presentation/publication?


In terms of incentives, what can we (afford to) offer them for their time? I'd like to think the experience alone would be satisfying, but the chances are they may get frustrated to.

**Comment by temjones** [comment]
I agree with Aoife's overall plan and Alex's examples, and I also think that it's going to be logistically easier to use our own machines for testing, at least initially. We can get an external mouse to eliminate track-pad confusion.

One thing that is emphasized quite a lot in the Krug books is the question of whether the "home page" tells the user what they can do. I think this is really important to keep in mind in our testing cycles and I would like if we allocate some time in our testing to ask the users about this. VFB 1.5, as shown by the screenshot Alex attached, has a very elegant and obvious section for the user to browse for this information. ("What can VFB do for me?"). Krug calls this the "Get it" testing - asking users, "what is the purpose / value / organization of this site?", as opposed to the "Key Task" type testing, which is largely what we have discussed so far. I think with VFB2's fairly minimalist design, this is going to be important feedback. We want to be able to appeal to relatively naive users as well as people who already have some idea of what the site can do for them.

Another thing I really liked in Krug's examples was the way he subtly phrases his task questions in ways that reinforce the idea that we aren't testing the _user_, we're testing the _site_. For example, "What would you do if you wanted to find out X..." sounds quite a bit less intimidating than "Can you  do X...". Even though we tell the user at the beginning that this isn't a test for them, I think it's good to keep reinforcing that idea with careful attention to the language we use in our questions.
