### ISSUE TITLE
Presentation/Discussion on UX testing for project meeting

### ISSUE THREAD

**Issue by ah963** [VirtualFlyBrain/VFB_UX#4]
Presentation 
What works, what are issues?
Breakdown issues into single tickets.

Discussion
Priorities
UX testing plan going forward

**Comment by aoifelarkin** [comment]
@dosumis @ah963 Not sure if we're having a chat about this at the standup later (or tomorrow/Monday) but have made a couple of slides about some ideas for the UX session at the project meeting, based on the meeting myself+Alex+Gillian had on Tuesday morning (attached).

[VFB_23Jan2017_UXtesting.pptx](https://github.com/VirtualFlyBrain/VFB_UX/files/1642630/VFB_23Jan2017_UXtesting.pptx)
